# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 171, 611))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.first_page_button = QtWidgets.QPushButton(self.layoutWidget)
        self.first_page_button.setMinimumSize(QtCore.QSize(0, 70))
        self.first_page_button.setSizeIncrement(QtCore.QSize(0, 0))
        self.first_page_button.setObjectName("first_page_button")
        self.verticalLayout.addWidget(self.first_page_button)
        self.second_page_button = QtWidgets.QPushButton(self.layoutWidget)
        self.second_page_button.setMinimumSize(QtCore.QSize(0, 70))
        self.second_page_button.setObjectName("second_page_button")
        self.verticalLayout.addWidget(self.second_page_button)
        self.third_page_button = QtWidgets.QPushButton(self.layoutWidget)
        self.third_page_button.setMinimumSize(QtCore.QSize(0, 70))
        self.third_page_button.setObjectName("third_page_button")
        self.verticalLayout.addWidget(self.third_page_button)
        self.forth_page_button = QtWidgets.QPushButton(self.layoutWidget)
        self.forth_page_button.setMinimumSize(QtCore.QSize(0, 70))
        self.forth_page_button.setObjectName("forth_page_button")
        self.verticalLayout.addWidget(self.forth_page_button)
        self.fifth_page_button = QtWidgets.QPushButton(self.layoutWidget)
        self.fifth_page_button.setMinimumSize(QtCore.QSize(0, 70))
        self.fifth_page_button.setObjectName("fifth_page_button")
        self.verticalLayout.addWidget(self.fifth_page_button)
        self.sixth_page_button = QtWidgets.QPushButton(self.layoutWidget)
        self.sixth_page_button.setMinimumSize(QtCore.QSize(0, 70))
        self.sixth_page_button.setObjectName("sixth_page_button")
        self.verticalLayout.addWidget(self.sixth_page_button)
        self.left_menu_label = QtWidgets.QLabel(Form)
        self.left_menu_label.setGeometry(QtCore.QRect(0, 30, 221, 691))
        self.left_menu_label.setText("")
        self.left_menu_label.setPixmap(QtGui.QPixmap("混合彩色竖屏.jpg"))
        self.left_menu_label.setObjectName("left_menu_label")
        self.first_page_widget = QtWidgets.QWidget(Form)
        self.first_page_widget.setGeometry(QtCore.QRect(259, 29, 981, 671))
        self.first_page_widget.setObjectName("first_page_widget")
        self.big_picture_label = QtWidgets.QLabel(self.first_page_widget)
        self.big_picture_label.setGeometry(QtCore.QRect(0, 0, 981, 351))
        self.big_picture_label.setText("")
        self.big_picture_label.setPixmap(QtGui.QPixmap("水彩插画.jpg"))
        self.big_picture_label.setObjectName("big_picture_label")
        self.tableView = QtWidgets.QTableView(self.first_page_widget)
        self.tableView.setGeometry(QtCore.QRect(0, 360, 981, 301))
        self.tableView.setObjectName("tableView")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(230, 30, 20, 691))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.top_menu_label = QtWidgets.QLabel(Form)
        self.top_menu_label.setGeometry(QtCore.QRect(0, 0, 1291, 31))
        self.top_menu_label.setText("")
        self.top_menu_label.setPixmap(QtGui.QPixmap("流线条艺术.jpg"))
        self.top_menu_label.setObjectName("top_menu_label")
        self.subtract_button = QtWidgets.QPushButton(Form)
        self.subtract_button.setGeometry(QtCore.QRect(1210, 0, 30, 30))
        self.subtract_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("subtract.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.subtract_button.setIcon(icon)
        self.subtract_button.setObjectName("subtract_button")
        self.close_button = QtWidgets.QPushButton(Form)
        self.close_button.setGeometry(QtCore.QRect(1250, 0, 30, 30))
        self.close_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon1)
        self.close_button.setObjectName("close_button")
        self.profile_button = QtWidgets.QPushButton(Form)
        self.profile_button.setGeometry(QtCore.QRect(1170, 0, 30, 30))
        self.profile_button.setToolTip("")
        self.profile_button.setWhatsThis("")
        self.profile_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("我的.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_button.setIcon(icon2)
        self.profile_button.setObjectName("profile_button")
        self.left_menu_label.raise_()
        self.layoutWidget.raise_()
        self.first_page_widget.raise_()
        self.line.raise_()
        self.top_menu_label.raise_()
        self.subtract_button.raise_()
        self.close_button.raise_()
        self.profile_button.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.first_page_button.setText(_translate("Form", "首页"))
        self.second_page_button.setText(_translate("Form", "挂号"))
        self.third_page_button.setText(_translate("Form", "咨询"))
        self.forth_page_button.setText(_translate("Form", "复诊"))
        self.fifth_page_button.setText(_translate("Form", "私人医生"))
        self.sixth_page_button.setText(_translate("Form", "在线药房"))

